version: "3"

services:
  app_lar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_lar
    image: app_lar
    tty: true
#    command: service php7.2-fpm start && service nginx restart
    volumes:
    - .:/usr/share/nginx/html
    - ./nginx:/etc/nginx/site-enabled
    ports:
    - "8080:80"
    depends_on:
    - mysql
    networks:
    - "net-lar"

  mysql:
    container_name: ${MYSQL_CONTAINER:-mysql_container_lar}
    image: mysql:${MYSQL_TAG:-5.7}
    ports:
    - "${MYSQL_PORT:-3307}:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=docker_laravel
    - MYSQL_DATABASE=docker_laravel
    - MYSQL_USER=docker_laravel
    - MYSQL_PASSWORD=docker_laravel
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    - ./mysql-data:/var/lib/mysql
    networks:
    - "net-lar"


#  phpfpm:
#    image: php:7.0.4-fpm
#    container_name: php_lar
#    volumes:
#    - .:/var/www/
#    working_dir: /var/www
#    entrypoint:
#    - php-fpm
#    networks:
#    - "net-lar"

#  nginx:
#    image: nginx:alpine
#    container_name: nginx_lar
#    volumes:
#    - .:/var/www
#    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#    - 8080:80
#    networks:
#    - "net-lar"

networks:
  net-lar:
